// ========================================================
// MA JI YOUNG EDITION & ATELIER Database
// Official Exhibition Archive: 《Moments》
// ========================================================

const GALLERY_DATA = {
  brand: {
    nameKr: "마지영 에디션",
    nameEn: "MA JI YOUNG EDITION",
    subTitle: "Atelier & Contemporary Art Archive",
    description: "삶의 구체적인 감정과 시간의 두께를 '단단한 물리적 유닛(Unit)'으로 환원하는 마지영 작가의 공식 아카이브 및 에디션 플랫폼입니다."
  },
  artist: {
    id: "ma-ji-young",
    nameKr: "마지영",
    nameEn: "MA JI YOUNG",
    photo: "assets/images/artist_ma_ji_young.png",
    studioPhoto: "assets/images/artist_ma_ji_young_studio.png",
    category: "Contemporary / Relief Monochrome",
    connects: [
      { label: "청목 미술관 공식 안내 (Cheongmok Museum)", url: "http://jbmuseum.or.kr/bbs/board.php?bo_table=b_01&wr_id=122&sfl=wr_4&stx=%EC%A0%84%EC%A3%BC&sop=and" },
      { label: "개인전 안내 (Solo Exhibition)", url: "#exhibition-section" },
      { label: "아틀리에 인스타그램 (Instagram)", url: "https://www.instagram.com/majiyoung_artist" }
    ],
    statementTitleKr: "Moments: 흔들리던 순간조차 찬란했던, 기억의 유닛(Unit)",
    statementTitleEn: "Moments: Even the Wavering Moments Were Radiant, Units of Memory",
    statementKr: [
      "이번 전시 컨셉 《Moments》는 관념적이고 난해한 형이상학에 매몰되기보다, 삶의 구체적인 감정과 시간의 두께를 ‘단단한 물리적 유닛(Unit)’이라는 구체적 물질로 환원하여 보여준다.",
      "화면을 구성하는 사각의 입체 모듈들은 독립된 색채와 붓질의 레이어를 품고 있는 개별적 회화 단위이다. 이는 저마다의 속도로 지나온 고독, 상실, 그리움, 그리고 치유의 순간들을 상징하며, 개별 유닛들이 촘촘히 군집을 이루어 하나의 생(生)의 무늬와 시간의 두께를 구축한다.",
      "단 하나의 순간으로 완성되는 삶은 없다. 불완전하게 흔들리고 마주하기 힘겨웠던 찰나들조차 겹겹이 쌓여 지금의 존재를 지탱하는 단단한 구조가 된다. 이번 전시는 회화적 모듈이 만들어내는 반복과 변주, 그리고 부조적 질감을 통해 지나온 기억의 조각들이 다정하게 우리의 삶과 교감하는 공간이다."
    ],
    statementEn: [
      "Rather than becoming buried in abstract and complex metaphysics, this exhibition renders the concrete emotions of life and the thickness of time into a tangible substance: 'solid physical units'.",
      "The square 3D modules forming the canvas are individual painted units, each carrying independent layers of color and brushwork. They symbolize the moments of solitude, loss, longing, and healing passed through at one's own pace; as these individual units densely cluster together, they construct a singular pattern of life and a depth of time.",
      "No life is completed in a single moment. Even those imperfectly wavering and painful moments accumulate layer upon layer, forming a solid structure that sustains our present existence. Through the repetition, variation, and relief-like texture generated by these painterly modules, this exhibition offers a space where fragments of past memories gently commune with our lives."
    ],
    exhibitions: [
      {
        id: "exb-mjy-1",
        title: "마지영 개인전 《Moments: 흔들리던 순간조차 찬란했던, 기억의 유닛》",
        venue: "청목 미술관 (Cheongmok Museum of Art)",
        venueUrl: "http://jbmuseum.or.kr/bbs/board.php?bo_table=b_01&wr_id=122&sfl=wr_4&stx=%EC%A0%84%EC%A3%BC&sop=and",
        date: "2026.10.13 – 2026.10.18",
        image: "assets/images/exhibition_moments_poster.png",
        badge: "SOLO EXHIBITION",
        description: "사각의 입체 우든 블록 모듈 위에 얹힌 독립된 색채와 붓질의 레이어로 시간의 두께와 생의 무늬를 증언하는 마지영 작가의 대규모 개인전."
      },
      {
        id: "exb-mjy-2",
        title: "동시대 부조 회화와 시간의 물질성 초대전",
        venue: "마지영 아틀리에 기획전시관",
        date: "2026.11.05 – 2026.12.20",
        image: "assets/images/artwork_moments_26_001.png",
        badge: "INVITATIONAL",
        description: "동시대 물질성과 부조 회화의 지평을 탐색하는 현대미술 작가 특별 초대전."
      },
      {
        id: "exb-mjy-3",
        title: "한국 현대 모듈러 아트 비엔날레 쇼케이스",
        venue: "서울 예술의전당 한가람미술관",
        date: "2025.10.01 – 2025.11.15",
        image: "assets/images/artwork_moments_26_003.png",
        badge: "GROUP EXHIBITION",
        description: "모듈러 아트의 구조적 확장과 공간적 변주를 선보인 주요 비엔날레 기획 전시."
      }
    ],
    stories: [
      {
        id: "story-mjy-1",
        title: "생(生)의 무늬를 쌓아올리는 기억의 모듈 — 마지영 작가의 《Moments》",
        date: "2026.09.24",
        image: "assets/images/artwork_moments_26_001.png",
        summary: "회화적 모듈이 빚어내는 반복과 변주, 그리고 묵직한 부조적 질감으로 마주하는 시간의 두께. 불완전했던 찰나들이 모여 지금의 존재를 지탱하는 단단한 유닛이 되다."
      },
      {
        id: "story-mjy-2",
        title: "목재 블록 위의 무한한 변주: 마지영의 우든 블록 믹스드미디어 기법 연구",
        date: "2026.08.15",
        image: "assets/images/artwork_moments_26_005.png",
        summary: "평면 캔버스의 한계를 넘어 3차원 큐브 유닛을 구축하고 그 위에 아크릴, 안료, 바니시를 겹겹이 중첩시켜 빛과 그림자의 호흡을 담아내는 제작 공정."
      }
    ],
    artworks: [
      {
        id: "MJY-26-001",
        title: "Moments 26-001",
        subTitle: "바람이 머무는 곳",
        subTitleEn: "Where the Wind Lingers",
        poemKr: "삶을 통째로 뒤흔들던 거친 폭풍이 지나가고,\n바람마저 고요해진 그 자리,\n비로소 마주하는 찬란한 잔상.",
        poemEn: "The fierce tempest that shook my entire being has passed,\nand in that space where even the wind has fallen still,\nI finally face the brilliant afterimage.",
        medium: "mixed media on wooden Blocks",
        size: "W 67.5 x H 40.0 cm",
        price: "8,500,000",
        badge: "ORIGINAL",
        category: "master",
        image: "assets/images/artwork_moments_26_001.png"
      },
      {
        id: "MJY-26-002",
        title: "Moments 26-002",
        subTitle: "바로 지금, 여기",
        subTitleEn: "Right Here, Right Now",
        poemKr: "어제와 내일의 소음을 걷어내고,\n오직 현재라는 찰나 위에 온전하게 깨어 있는.",
        poemEn: "Clearing away the noise of yesterday and tomorrow,\nawaken fully and existing solely upon\nthis fleeting moment.",
        medium: "mixed media on wooden Blocks",
        size: "W 17.5 x H 27.5 cm",
        price: "3,800,000",
        badge: "ORIGINAL",
        category: "master",
        image: "assets/images/artwork_moments_26_002.png"
      },
      {
        id: "MJY-26-003",
        title: "Moments 26-003",
        subTitle: "중심을 지키는 것",
        subTitleEn: "Finding the Center",
        poemKr: "때로 중심을 잃고 미로를 헤맬지라도,\n마침내 제자리로 귀환하는 내면의 중력.",
        poemEn: "Though one may lose the core and wander\nThrough a labyrinth at times,\nthe inner gravity that holds true,\nfinally pulling back home to the center.",
        medium: "mixed media on wooden Blocks",
        size: "W 57.5 x H 37.5 cm",
        price: "7,200,000",
        badge: "ORIGINAL",
        category: "master",
        image: "assets/images/artwork_moments_26_003.png"
      },
      {
        id: "MJY-26-004",
        title: "Moments 26-004",
        subTitle: "중심을 지키는 것",
        subTitleEn: "Finding the Center",
        poemKr: "때로 중심을 잃고 미로를 헤맬지라도,\n마침내 제자리로 귀환하는 내면의 중력.",
        poemEn: "Though one may lose the core and wander\nThrough a labyrinth at times,\nthe inner gravity that holds true,\nfinally pulling back home to the center.",
        medium: "mixed media on wooden Blocks",
        size: "W 30.0 x H 16.0 cm",
        price: "4,200,000",
        badge: "ORIGINAL",
        category: "master",
        image: "assets/images/artwork_moments_26_004.png"
      },
      {
        id: "MJY-26-005",
        title: "Moments 26-005",
        subTitle: "흐름에 맡기는 힘",
        subTitleEn: "The Power of Yielding to the Flow",
        poemKr: "억지로 밀어붙이지 않을 때 흐르는 순리,\n쥔 손을 내려놓는 순간\n스스로 이루어지기 시작한다.",
        poemEn: "The natural flow found only when one stops forcing,\nthe moment tight fists are released,\nit begins to fulfill itself.",
        medium: "mixed media on wooden Blocks",
        size: "W 20.0 x H 35.0 cm",
        price: "4,600,000",
        badge: "ORIGINAL",
        category: "master",
        image: "assets/images/artwork_moments_26_005.png"
      },
      {
        id: "MJY-26-006",
        title: "Moments 26-006",
        subTitle: "무제",
        subTitleEn: "Untitled",
        poemKr: "언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.\n마주 선 시선과 마음이 닿는 그대로 머물기를.",
        poemEn: "Language at times confines the boundless layers\nof emotion into a single frame.\nMay you simply linger where your gaze\nand heart naturally reach.",
        medium: "mixed media on wooden Blocks",
        size: "W 27.5 x H 27.5 cm",
        price: "4,900,000",
        badge: "ORIGINAL",
        category: "master",
        image: "assets/images/artwork_moments_26_006.png"
      },
      {
        id: "MJY-26-007",
        title: "Moments 26-007",
        subTitle: "무제",
        subTitleEn: "Untitled",
        poemKr: "언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.\n마주 선 시선과 마음이 닿는 그대로 머물기를.",
        poemEn: "Language at times confines the boundless layers of emotion into a single frame.\nMay you simply linger where your gaze and heart naturally reach.",
        medium: "mixed media on wooden Blocks",
        size: "W 27.5 x H 27.5 cm",
        price: "4,900,000",
        badge: "ORIGINAL",
        category: "master",
        image: "assets/images/artwork_moments_26_007.png"
      },
      {
        id: "MJY-26-008",
        title: "Moments 26-008",
        subTitle: "무제",
        subTitleEn: "Untitled",
        poemKr: "언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.\n마주 선 시선과 마음이 닿는 그대로 머물기를.",
        poemEn: "Language at times confines the boundless layers of emotion into a single frame.\nMay you simply linger where your gaze and heart naturally reach.",
        medium: "mixed media on wooden Blocks",
        size: "W 27.5 x H 27.5 cm",
        price: "4,900,000",
        badge: "ORIGINAL",
        category: "master",
        image: "assets/images/artwork_moments_26_008.png"
      },
      {
        id: "MJY-26-009",
        title: "Moments 26-009",
        subTitle: "무제",
        subTitleEn: "Untitled",
        poemKr: "언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.\n마주 선 시선과 마음이 닿는 그대로 머물기를.",
        poemEn: "Language at times confines the boundless layers of emotion into a single frame.\nMay you simply linger where your gaze and heart naturally reach.",
        medium: "mixed media on wooden Blocks",
        size: "W 25.0 x H 25.0 cm",
        price: "4,300,000",
        badge: "ORIGINAL",
        category: "master",
        image: "assets/images/artwork_moments_26_009.png"
      },
      {
        id: "MJY-26-010",
        title: "Moments 26-010",
        subTitle: "무제",
        subTitleEn: "Untitled",
        poemKr: "언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.\n마주 선 시선과 마음이 닿는 그대로 머물기를.",
        poemEn: "Language at times confines the boundless layers of emotion into a single frame.\nMay you simply linger where your gaze and heart naturally reach.",
        medium: "mixed media on wooden Blocks",
        size: "W 25.0 x H 25.0 cm",
        price: "4,300,000",
        badge: "ORIGINAL",
        category: "master",
        image: "assets/images/artwork_moments_26_010.png"
      },
      {
        id: "MJY-26-011-014",
        title: "Moments 26-011 ~ 014",
        subTitle: "무제 (4연작 세트)",
        subTitleEn: "Untitled (Modular Set of 4)",
        poemKr: "언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.\n마주 선 시선과 마음이 닿는 그대로 머물기를.",
        poemEn: "Language at times confines the boundless layers of emotion into a single frame.",
        medium: "mixed media on wooden Blocks",
        size: "W 15.0 x H 12.5 cm (each, 4pcs)",
        price: "6,400,000",
        badge: "EDITION",
        category: "modular",
        image: "assets/images/artwork_moments_26_011_014_a.png"
      },
      {
        id: "MJY-26-015-018",
        title: "Moments 26-015 ~ 018",
        subTitle: "무제 (4연작 세트)",
        subTitleEn: "Untitled (Modular Set of 4)",
        poemKr: "언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.\n마주 선 시선과 마음이 닿는 그대로 머물기를.",
        poemEn: "Language at times confines the boundless layers of emotion into a single frame.",
        medium: "mixed media on wooden Blocks",
        size: "W 15.0 x H 12.5 cm (each, 4pcs)",
        price: "6,400,000",
        badge: "EDITION",
        category: "modular",
        image: "assets/images/artwork_moments_26_015_018_a.png"
      },
      {
        id: "MJY-26-019-022",
        title: "Moments 26-019 ~ 022",
        subTitle: "무제 (4연작 세트)",
        subTitleEn: "Untitled (Modular Set of 4)",
        poemKr: "언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.\n마주 선 시선과 마음이 닿는 그대로 머물기를.",
        poemEn: "Language at times confines the boundless layers of emotion into a single frame.",
        medium: "mixed media on wooden Blocks",
        size: "W 15.0 x H 12.5 cm (each, 4pcs)",
        price: "6,400,000",
        badge: "EDITION",
        category: "modular",
        image: "assets/images/artwork_moments_26_019_022_a.png"
      },
      {
        id: "MJY-26-023-026",
        title: "Moments 26-023 ~ 026",
        subTitle: "무제 (4연작 세트)",
        subTitleEn: "Untitled (Modular Set of 4)",
        poemKr: "언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.\n마주 선 시선과 마음이 닿는 그대로 머물기를.",
        poemEn: "Language at times confines the boundless layers of emotion into a single frame.",
        medium: "mixed media on wooden Blocks",
        size: "W 15.0 x H 12.5 cm (each, 4pcs)",
        price: "6,400,000",
        badge: "EDITION",
        category: "modular",
        image: "assets/images/artwork_moments_26_023_026_a.png"
      },
      {
        id: "MJY-26-027-030",
        title: "Moments 26-027 ~ 030",
        subTitle: "무제 (4연작 세트)",
        subTitleEn: "Untitled (Modular Set of 4)",
        poemKr: "언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.\n마주 선 시선과 마음이 닿는 그대로 머물기를.",
        poemEn: "Language at times confines the boundless layers of emotion into a single frame.",
        medium: "mixed media on wooden Blocks",
        size: "W 15.0 x H 12.5 cm (each, 4pcs)",
        price: "6,400,000",
        badge: "EDITION",
        category: "modular",
        image: "assets/images/artwork_moments_26_027_030_a.png"
      },
      {
        id: "MJY-26-031-034",
        title: "Moments 26-031 ~ 034",
        subTitle: "무제 (4연작 세트)",
        subTitleEn: "Untitled (Modular Set of 4)",
        poemKr: "언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.\n마주 선 시선과 마음이 닿는 그대로 머물기를.",
        poemEn: "Language at times confines the boundless layers of emotion into a single frame.",
        medium: "mixed media on wooden Blocks",
        size: "W 15.0 x H 12.5 cm (each, 4pcs)",
        price: "6,400,000",
        badge: "EDITION",
        category: "modular",
        image: "assets/images/artwork_moments_26_031_034_a.png"
      },
      {
        id: "MJY-26-035-036",
        title: "Moments 26-035 ~ 036",
        subTitle: "무제 (2연작 듀오)",
        subTitleEn: "Untitled (Duo Blocks of 2)",
        poemKr: "언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.\n마주 선 시선과 마음이 닿는 그대로 머물기를.",
        poemEn: "Language at times confines the boundless layers of emotion into a single frame.",
        medium: "mixed media on wooden Blocks",
        size: "W 15.0 x H 25.0 cm (each, 2pcs)",
        price: "4,800,000",
        badge: "EDITION",
        category: "duo",
        image: "assets/images/artwork_moments_26_035_036_a.png"
      },
      {
        id: "MJY-26-037-038",
        title: "Moments 26-037 ~ 038",
        subTitle: "무제 (2연작 듀오)",
        subTitleEn: "Untitled (Duo Blocks of 2)",
        poemKr: "언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.\n마주 선 시선과 마음이 닿는 그대로 머물기를.",
        poemEn: "Language at times confines the boundless layers of emotion into a single frame.",
        medium: "mixed media on wooden Blocks",
        size: "W 15.0 x H 25.0 cm (each, 2pcs)",
        price: "4,800,000",
        badge: "EDITION",
        category: "duo",
        image: "assets/images/artwork_moments_26_037_038_a.png"
      },
      {
        id: "MJY-26-039-040",
        title: "Moments 26-039 ~ 040",
        subTitle: "무제 (2연작 듀오)",
        subTitleEn: "Untitled (Duo Blocks of 2)",
        poemKr: "언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.\n마주 선 시선과 마음이 닿는 그대로 머물기를.",
        poemEn: "Language at times confines the boundless layers of emotion into a single frame.",
        medium: "mixed media on wooden Blocks",
        size: "W 15.0 x H 25.0 cm (each, 2pcs)",
        price: "4,800,000",
        badge: "EDITION",
        category: "duo",
        image: "assets/images/artwork_moments_26_039_040_a.png"
      },
      {
        id: "MJY-26-041-042",
        title: "Moments 26-041 ~ 042",
        subTitle: "무제 (2연작 듀오)",
        subTitleEn: "Untitled (Duo Blocks of 2)",
        poemKr: "언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.\n마주 선 시선과 마음이 닿는 그대로 머물기를.",
        poemEn: "Language at times confines the boundless layers of emotion into a single frame.",
        medium: "mixed media on wooden Blocks",
        size: "W 14.0 x H 14.0 cm (each, 2pcs)",
        price: "3,600,000",
        badge: "EDITION",
        category: "duo",
        image: "assets/images/artwork_moments_26_041_042_a.png"
      }
    ]
  },
  trendingKeywords: [
    "마지영", "Moments", "청목미술관", "기억의유닛", "우든블록", "릴리프회화", "바람이머무는곳", "바로지금여기", "중심을지키는것", "흐름에맡기는힘", "믹스드미디어"
  ],
  featuredCollections: [
    { id: "master", name: "Moments 26 대표작", thumb: "assets/images/artwork_moments_26_001.png", desc: "바람이 머무는 곳 & 중심을 지키는 것" },
    { id: "modular", name: "4연작 모듈 세트", thumb: "assets/images/artwork_moments_26_011_014_a.png", desc: "독립된 색채와 붓질 레이어의 군집" },
    { id: "duo", name: "2연작 듀오 블록", thumb: "assets/images/artwork_moments_26_035_036_a.png", desc: "시간의 두께와 균형을 이루는 모듈" }
  ]
};
