-- ========================================================
-- MA JI YOUNG EDITION & ATELIER
-- Supabase PostgreSQL Seed Data
-- 100% Lossless Migration from data.js
-- ========================================================

-- 1. SEED: site_settings
INSERT INTO site_settings (
    id, brand_name_kr, brand_name_en, sub_title, description,
    contact_email, contact_phone, address_kr, banner_active,
    banner_text_kr, banner_text_en
) VALUES (
    'default',
    '마지영 에디션',
    'MA JI YOUNG EDITION',
    'Atelier & Contemporary Art Archive',
    '삶의 구체적인 감정과 시간의 두께를 ''단단한 물리적 유닛(Unit)''으로 환원하는 마지영 작가의 공식 아카이브 및 에디션 플랫폼입니다.',
    'contact@majiyoung-edition.art',
    '063-228-8422',
    '전북특별자치도 전주시 완산구 유연로 87 청목빌딩',
    TRUE,
    '마지영 개인전 《Moments》 청목미술관 2026.10.13 - 10.18 개최',
    'MA JI YOUNG Solo Exhibition 《Moments》 at Cheongmok Museum of Art'
) ON CONFLICT (id) DO UPDATE SET
    brand_name_kr = EXCLUDED.brand_name_kr,
    brand_name_en = EXCLUDED.brand_name_en,
    sub_title = EXCLUDED.sub_title,
    description = EXCLUDED.description;

-- 2. SEED: artist_profiles
INSERT INTO artist_profiles (
    id, name_kr, name_en, photo_url, studio_photo_url, category,
    statement_title_kr, statement_title_en,
    statement_kr, statement_en, connect_links
) VALUES (
    'ma-ji-young',
    '마지영',
    'MA JI YOUNG',
    'assets/images/artist_ma_ji_young.png',
    'assets/images/artist_ma_ji_young_studio.png',
    'Contemporary / Relief Monochrome',
    'Moments: 흔들리던 순간조차 찬란했던, 기억의 유닛(Unit)',
    'Moments: Even the Wavering Moments Were Radiant, Units of Memory',
    '["이번 전시 컨셉 《Moments》는 관념적이고 난해한 형이상학에 매몰되기보다, 삶의 구체적인 감정과 시간의 두께를 ‘단단한 물리적 유닛(Unit)’이라는 구체적 물질로 환원하여 보여준다.","화면을 구성하는 사각의 입체 모듈들은 독립된 색채와 붓질의 레이어를 품고 있는 개별적 회화 단위이다. 이는 저마다의 속도로 지나온 고독, 상실, 그리움, 그리고 치유의 순간들을 상징하며, 개별 유닛들이 촘촘히 군집을 이루어 하나의 생(生)의 무늬와 시간의 두께를 구축한다.","단 하나의 순간으로 완성되는 삶은 없다. 불완전하게 흔들리고 마주하기 힘겨웠던 찰나들조차 겹겹이 쌓여 지금의 존재를 지탱하는 단단한 구조가 된다. 이번 전시는 회화적 모듈이 만들어내는 반복과 변주, 그리고 부조적 질감을 통해 지나온 기억의 조각들이 다정하게 우리의 삶과 교감하는 공간이다."]'::jsonb,
    '["Rather than becoming buried in abstract and complex metaphysics, this exhibition renders the concrete emotions of life and the thickness of time into a tangible substance: ''solid physical units''.","The square 3D modules forming the canvas are individual painted units, each carrying independent layers of color and brushwork. They symbolize the moments of solitude, loss, longing, and healing passed through at one''s own pace; as these individual units densely cluster together, they construct a singular pattern of life and a depth of time.","No life is completed in a single moment. Even those imperfectly wavering and painful moments accumulate layer upon layer, forming a solid structure that sustains our present existence. Through the repetition, variation, and relief-like texture generated by these painterly modules, this exhibition offers a space where fragments of past memories gently commune with our lives."]'::jsonb,
    '[{"label":"청목 미술관 공식 안내 (Cheongmok Museum)","url":"http://jbmuseum.or.kr/bbs/board.php?bo_table=b_01&wr_id=122&sfl=wr_4&stx=%EC%A0%84%EC%A3%BC&sop=and"},{"label":"개인전 안내 (Solo Exhibition)","url":"#exhibition-section"},{"label":"아틀리에 인스타그램 (Instagram)","url":"https://www.instagram.com/majiyoung_artist"}]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
    statement_kr = EXCLUDED.statement_kr,
    statement_en = EXCLUDED.statement_en,
    connect_links = EXCLUDED.connect_links;

-- 3. SEED: exhibitions
INSERT INTO exhibitions (
    id, title, venue, venue_url, period_date, image_url, badge, description, display_order, is_active
) VALUES (
    'exb-mjy-1',
    '마지영 개인전 《Moments: 흔들리던 순간조차 찬란했던, 기억의 유닛》',
    '청목 미술관 (Cheongmok Museum of Art)',
    'http://jbmuseum.or.kr/bbs/board.php?bo_table=b_01&wr_id=122&sfl=wr_4&stx=%EC%A0%84%EC%A3%BC&sop=and',
    '2026.10.13 – 2026.10.18',
    'assets/images/exhibition_moments_poster.png',
    'SOLO EXHIBITION',
    '사각의 입체 우든 블록 모듈 위에 얹힌 독립된 색채와 붓질의 레이어로 시간의 두께와 생의 무늬를 증언하는 마지영 작가의 대규모 개인전.',
    1,
    TRUE
) ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    venue = EXCLUDED.venue,
    period_date = EXCLUDED.period_date,
    image_url = EXCLUDED.image_url,
    description = EXCLUDED.description;

INSERT INTO exhibitions (
    id, title, venue, venue_url, period_date, image_url, badge, description, display_order, is_active
) VALUES (
    'exb-mjy-2',
    '동시대 부조 회화와 시간의 물질성 초대전',
    '마지영 아틀리에 기획전시관',
    '',
    '2026.11.05 – 2026.12.20',
    'assets/images/artwork_moments_26_001.png',
    'INVITATIONAL',
    '동시대 물질성과 부조 회화의 지평을 탐색하는 현대미술 작가 특별 초대전.',
    2,
    TRUE
) ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    venue = EXCLUDED.venue,
    period_date = EXCLUDED.period_date,
    image_url = EXCLUDED.image_url,
    description = EXCLUDED.description;

INSERT INTO exhibitions (
    id, title, venue, venue_url, period_date, image_url, badge, description, display_order, is_active
) VALUES (
    'exb-mjy-3',
    '한국 현대 모듈러 아트 비엔날레 쇼케이스',
    '서울 예술의전당 한가람미술관',
    '',
    '2025.10.01 – 2025.11.15',
    'assets/images/artwork_moments_26_003.png',
    'GROUP EXHIBITION',
    '모듈러 아트의 구조적 확장과 공간적 변주를 선보인 주요 비엔날레 기획 전시.',
    3,
    TRUE
) ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    venue = EXCLUDED.venue,
    period_date = EXCLUDED.period_date,
    image_url = EXCLUDED.image_url,
    description = EXCLUDED.description;

-- 4. SEED: artworks (All 42 Works)
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-001',
    'Moments 26-001',
    'Moments 26-001 - 바람이 머무는 곳',
    'Where the Wind Lingers',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 67.5 x H 40.0 cm',
    '{"w":67.5,"h":40,"unit":"cm"}'::jsonb,
    8500000,
    'available',
    '삶을 통째로 뒤흔들던 거친 폭풍이 지나가고,
바람마저 고요해진 그 자리,
비로소 마주하는 찬란한 잔상.',
    'The fierce tempest that shook my entire being has passed,
and in that space where even the wind has fallen still,
I finally face the brilliant afterimage.',
    'assets/images/artwork_moments_26_001.png',
    ARRAY['Moments', 'ORIGINAL', 'master'],
    TRUE,
    1
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-002',
    'Moments 26-002',
    'Moments 26-002 - 바로 지금, 여기',
    'Right Here, Right Now',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 17.5 x H 27.5 cm',
    '{"w":17.5,"h":27.5,"unit":"cm"}'::jsonb,
    3800000,
    'available',
    '어제와 내일의 소음을 걷어내고,
오직 현재라는 찰나 위에 온전하게 깨어 있는.',
    'Clearing away the noise of yesterday and tomorrow,
awaken fully and existing solely upon
this fleeting moment.',
    'assets/images/artwork_moments_26_002.png',
    ARRAY['Moments', 'ORIGINAL', 'master'],
    TRUE,
    2
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-003',
    'Moments 26-003',
    'Moments 26-003 - 중심을 지키는 것',
    'Finding the Center',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 57.5 x H 37.5 cm',
    '{"w":57.5,"h":37.5,"unit":"cm"}'::jsonb,
    7200000,
    'available',
    '때로 중심을 잃고 미로를 헤맬지라도,
마침내 제자리로 귀환하는 내면의 중력.',
    'Though one may lose the core and wander
Through a labyrinth at times,
the inner gravity that holds true,
finally pulling back home to the center.',
    'assets/images/artwork_moments_26_003.png',
    ARRAY['Moments', 'ORIGINAL', 'master'],
    TRUE,
    3
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-004',
    'Moments 26-004',
    'Moments 26-004 - 중심을 지키는 것',
    'Finding the Center',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 30.0 x H 16.0 cm',
    '{"w":30,"h":16,"unit":"cm"}'::jsonb,
    4200000,
    'available',
    '때로 중심을 잃고 미로를 헤맬지라도,
마침내 제자리로 귀환하는 내면의 중력.',
    'Though one may lose the core and wander
Through a labyrinth at times,
the inner gravity that holds true,
finally pulling back home to the center.',
    'assets/images/artwork_moments_26_004.png',
    ARRAY['Moments', 'ORIGINAL', 'master'],
    TRUE,
    4
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-005',
    'Moments 26-005',
    'Moments 26-005 - 흐름에 맡기는 힘',
    'The Power of Yielding to the Flow',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 20.0 x H 35.0 cm',
    '{"w":20,"h":35,"unit":"cm"}'::jsonb,
    4600000,
    'available',
    '억지로 밀어붙이지 않을 때 흐르는 순리,
쥔 손을 내려놓는 순간
스스로 이루어지기 시작한다.',
    'The natural flow found only when one stops forcing,
the moment tight fists are released,
it begins to fulfill itself.',
    'assets/images/artwork_moments_26_005.png',
    ARRAY['Moments', 'ORIGINAL', 'master'],
    FALSE,
    5
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-006',
    'Moments 26-006',
    'Moments 26-006 - 무제',
    'Untitled',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 27.5 x H 27.5 cm',
    '{"w":27.5,"h":27.5,"unit":"cm"}'::jsonb,
    4900000,
    'available',
    '언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.
마주 선 시선과 마음이 닿는 그대로 머물기를.',
    'Language at times confines the boundless layers
of emotion into a single frame.
May you simply linger where your gaze
and heart naturally reach.',
    'assets/images/artwork_moments_26_006.png',
    ARRAY['Moments', 'ORIGINAL', 'master'],
    FALSE,
    6
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-007',
    'Moments 26-007',
    'Moments 26-007 - 무제',
    'Untitled',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 27.5 x H 27.5 cm',
    '{"w":27.5,"h":27.5,"unit":"cm"}'::jsonb,
    4900000,
    'available',
    '언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.
마주 선 시선과 마음이 닿는 그대로 머물기를.',
    'Language at times confines the boundless layers of emotion into a single frame.
May you simply linger where your gaze and heart naturally reach.',
    'assets/images/artwork_moments_26_007.png',
    ARRAY['Moments', 'ORIGINAL', 'master'],
    FALSE,
    7
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-008',
    'Moments 26-008',
    'Moments 26-008 - 무제',
    'Untitled',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 27.5 x H 27.5 cm',
    '{"w":27.5,"h":27.5,"unit":"cm"}'::jsonb,
    4900000,
    'available',
    '언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.
마주 선 시선과 마음이 닿는 그대로 머물기를.',
    'Language at times confines the boundless layers of emotion into a single frame.
May you simply linger where your gaze and heart naturally reach.',
    'assets/images/artwork_moments_26_008.png',
    ARRAY['Moments', 'ORIGINAL', 'master'],
    FALSE,
    8
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-009',
    'Moments 26-009',
    'Moments 26-009 - 무제',
    'Untitled',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 25.0 x H 25.0 cm',
    '{"w":25,"h":25,"unit":"cm"}'::jsonb,
    4300000,
    'available',
    '언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.
마주 선 시선과 마음이 닿는 그대로 머물기를.',
    'Language at times confines the boundless layers of emotion into a single frame.
May you simply linger where your gaze and heart naturally reach.',
    'assets/images/artwork_moments_26_009.png',
    ARRAY['Moments', 'ORIGINAL', 'master'],
    FALSE,
    9
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-010',
    'Moments 26-010',
    'Moments 26-010 - 무제',
    'Untitled',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 25.0 x H 25.0 cm',
    '{"w":25,"h":25,"unit":"cm"}'::jsonb,
    4300000,
    'available',
    '언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.
마주 선 시선과 마음이 닿는 그대로 머물기를.',
    'Language at times confines the boundless layers of emotion into a single frame.
May you simply linger where your gaze and heart naturally reach.',
    'assets/images/artwork_moments_26_010.png',
    ARRAY['Moments', 'ORIGINAL', 'master'],
    FALSE,
    10
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-011-014',
    'Moments 26-011 ~ 014',
    'Moments 26-011 ~ 014 - 무제 (4연작 세트)',
    'Untitled (Modular Set of 4)',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 15.0 x H 12.5 cm (each, 4pcs)',
    '{"w":15,"h":12.5,"unit":"cm"}'::jsonb,
    6400000,
    'available',
    '언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.
마주 선 시선과 마음이 닿는 그대로 머물기를.',
    'Language at times confines the boundless layers of emotion into a single frame.',
    'assets/images/artwork_moments_26_011_014_a.png',
    ARRAY['Moments', 'EDITION', 'modular'],
    FALSE,
    11
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-015-018',
    'Moments 26-015 ~ 018',
    'Moments 26-015 ~ 018 - 무제 (4연작 세트)',
    'Untitled (Modular Set of 4)',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 15.0 x H 12.5 cm (each, 4pcs)',
    '{"w":15,"h":12.5,"unit":"cm"}'::jsonb,
    6400000,
    'available',
    '언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.
마주 선 시선과 마음이 닿는 그대로 머물기를.',
    'Language at times confines the boundless layers of emotion into a single frame.',
    'assets/images/artwork_moments_26_015_018_a.png',
    ARRAY['Moments', 'EDITION', 'modular'],
    FALSE,
    12
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-019-022',
    'Moments 26-019 ~ 022',
    'Moments 26-019 ~ 022 - 무제 (4연작 세트)',
    'Untitled (Modular Set of 4)',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 15.0 x H 12.5 cm (each, 4pcs)',
    '{"w":15,"h":12.5,"unit":"cm"}'::jsonb,
    6400000,
    'available',
    '언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.
마주 선 시선과 마음이 닿는 그대로 머물기를.',
    'Language at times confines the boundless layers of emotion into a single frame.',
    'assets/images/artwork_moments_26_019_022_a.png',
    ARRAY['Moments', 'EDITION', 'modular'],
    FALSE,
    13
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-023-026',
    'Moments 26-023 ~ 026',
    'Moments 26-023 ~ 026 - 무제 (4연작 세트)',
    'Untitled (Modular Set of 4)',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 15.0 x H 12.5 cm (each, 4pcs)',
    '{"w":15,"h":12.5,"unit":"cm"}'::jsonb,
    6400000,
    'available',
    '언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.
마주 선 시선과 마음이 닿는 그대로 머물기를.',
    'Language at times confines the boundless layers of emotion into a single frame.',
    'assets/images/artwork_moments_26_023_026_a.png',
    ARRAY['Moments', 'EDITION', 'modular'],
    FALSE,
    14
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-027-030',
    'Moments 26-027 ~ 030',
    'Moments 26-027 ~ 030 - 무제 (4연작 세트)',
    'Untitled (Modular Set of 4)',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 15.0 x H 12.5 cm (each, 4pcs)',
    '{"w":15,"h":12.5,"unit":"cm"}'::jsonb,
    6400000,
    'available',
    '언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.
마주 선 시선과 마음이 닿는 그대로 머물기를.',
    'Language at times confines the boundless layers of emotion into a single frame.',
    'assets/images/artwork_moments_26_027_030_a.png',
    ARRAY['Moments', 'EDITION', 'modular'],
    FALSE,
    15
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-031-034',
    'Moments 26-031 ~ 034',
    'Moments 26-031 ~ 034 - 무제 (4연작 세트)',
    'Untitled (Modular Set of 4)',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 15.0 x H 12.5 cm (each, 4pcs)',
    '{"w":15,"h":12.5,"unit":"cm"}'::jsonb,
    6400000,
    'available',
    '언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.
마주 선 시선과 마음이 닿는 그대로 머물기를.',
    'Language at times confines the boundless layers of emotion into a single frame.',
    'assets/images/artwork_moments_26_031_034_a.png',
    ARRAY['Moments', 'EDITION', 'modular'],
    FALSE,
    16
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-035-036',
    'Moments 26-035 ~ 036',
    'Moments 26-035 ~ 036 - 무제 (2연작 듀오)',
    'Untitled (Duo Blocks of 2)',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 15.0 x H 25.0 cm (each, 2pcs)',
    '{"w":15,"h":25,"unit":"cm"}'::jsonb,
    4800000,
    'available',
    '언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.
마주 선 시선과 마음이 닿는 그대로 머물기를.',
    'Language at times confines the boundless layers of emotion into a single frame.',
    'assets/images/artwork_moments_26_035_036_a.png',
    ARRAY['Moments', 'EDITION', 'duo'],
    FALSE,
    17
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-037-038',
    'Moments 26-037 ~ 038',
    'Moments 26-037 ~ 038 - 무제 (2연작 듀오)',
    'Untitled (Duo Blocks of 2)',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 15.0 x H 25.0 cm (each, 2pcs)',
    '{"w":15,"h":25,"unit":"cm"}'::jsonb,
    4800000,
    'available',
    '언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.
마주 선 시선과 마음이 닿는 그대로 머물기를.',
    'Language at times confines the boundless layers of emotion into a single frame.',
    'assets/images/artwork_moments_26_037_038_a.png',
    ARRAY['Moments', 'EDITION', 'duo'],
    FALSE,
    18
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-039-040',
    'Moments 26-039 ~ 040',
    'Moments 26-039 ~ 040 - 무제 (2연작 듀오)',
    'Untitled (Duo Blocks of 2)',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 15.0 x H 25.0 cm (each, 2pcs)',
    '{"w":15,"h":25,"unit":"cm"}'::jsonb,
    4800000,
    'available',
    '언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.
마주 선 시선과 마음이 닿는 그대로 머물기를.',
    'Language at times confines the boundless layers of emotion into a single frame.',
    'assets/images/artwork_moments_26_039_040_a.png',
    ARRAY['Moments', 'EDITION', 'duo'],
    FALSE,
    19
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
INSERT INTO artworks (
    id, code, title_kr, title_en, series, medium, year, size_spec, dimensions,
    price, status, description_kr, description_en, image_url, tags, is_featured, display_order
) VALUES (
    'MJY-26-041-042',
    'Moments 26-041 ~ 042',
    'Moments 26-041 ~ 042 - 무제 (2연작 듀오)',
    'Untitled (Duo Blocks of 2)',
    '대표작 (Master Collection)',
    'mixed media on wooden Blocks',
    2026,
    'W 14.0 x H 14.0 cm (each, 2pcs)',
    '{"w":14,"h":14,"unit":"cm"}'::jsonb,
    3600000,
    'available',
    '언어는 때로 무한한 감정의 결을 하나의 틀에 가두곤 합니다.
마주 선 시선과 마음이 닿는 그대로 머물기를.',
    'Language at times confines the boundless layers of emotion into a single frame.',
    'assets/images/artwork_moments_26_041_042_a.png',
    ARRAY['Moments', 'EDITION', 'duo'],
    FALSE,
    20
) ON CONFLICT (id) DO UPDATE SET
    title_kr = EXCLUDED.title_kr,
    title_en = EXCLUDED.title_en,
    series = EXCLUDED.series,
    price = EXCLUDED.price,
    description_kr = EXCLUDED.description_kr,
    description_en = EXCLUDED.description_en,
    image_url = EXCLUDED.image_url;
